version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: okt@mail.ru
      PGADMIN_DEFAULT_PASSWORD: oktpass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - 8080:80
    networks:
      - postgres
    restart: unless-stopped

  graphqlapp:
    container_name: graphql_container
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
      - postgres
    depends_on:
      - postgres



networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
